### ISSUE TITLE
Some problems about security

### ISSUE THREAD

**Issue by awcyvan** [zhiguai/CZ-LoveCards#3]
When my friends were developing with your framework, they wanted me to test their website for bugs (my friends are not very good at PHP programming), then I found some problems with cross-site scripting attacks, or also called "XSS". In more detail, when I enter "<IFRAME SRC=javascript:alert(&#039xss&#039)>" in the search box and click the button, the page will display an alert. Also, when I enter "<IFRAME SRC=javascript:window.history.back(-1)>" in the content input of the confession wall, the JavaScript will run as expected, and then, others cannot enter the home page (the page will jump to its previous page). My friends think you might be able to add a protection system of network attack, but maybe it's unnecessary, who will attack a confession wall? But my friends think it's a no small problem, so I wrote this issue. In my opinion this won't be a big problem, but who knows? :-)

**Comment by zhiguai** [comment]
> When my friends were developing with your framework, they wanted me to test their website for bugs (my friends are not very good at PHP programming), then I found some problems with cross-site scripting attacks, or also called "XSS". In more detail, when I enter "<IFRAME SRC=javascript:alert(&#039xss&#039)>" in the search box and click the button, the page will display an alert. Also, when I enter "<IFRAME SRC=javascript:window.history.back(-1)>" in the content input of the confession wall, the JavaScript will run as expected, and then, others cannot enter the home page (the page will jump to its previous page). My friends think you might be able to add a protection system of network attack, but maybe it's unnecessary, who will attack a confession wall? But my friends think it's a no small problem, so I wrote this issue. In my opinion this won't be a big problem, but who knows? :-)

Thank you for reminding me. First of all, I'm surprised. I don't know if you are a developer from China, because I haven't made any versions about other languages. Then, as early as a year ago, a developer from China reported this problem to me, and I also released the patch code to QQ users in time, but it was not synchronized to github. There are two reasons. First, the current framework code is too old and there are other loopholes. Second, the development of the second-generation framework was already ready, so I stopped synchronizing with github. Today, the development of the second-generation framework is coming to an end and will be released in the near future. If you want to pay attention to the progress of this project, or get the current version of xss vulnerability patch code, you can contact me with 2903074366@qq.com by joining QQ group or email. Finally, if you are not from China, I am very glad that friends from all over the world have used my program. I want to contact you for more information so that I can better make a version that conforms to various countries.

**Comment by awcyvan** [comment]
Thank you. I've already told my friend this. By the way, my friends are Chinese, I just help them find loopholes. Any way I think this is a great project. :-)
